version: '3.8' # Thêm lại version nếu cần

services:
  skg-management:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - skg-management-postgres
    ports:
      - '7000:7000'
    networks:
      - backend

  skg-management-postgres:
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    ports:
      - '54335:5432'
    environment:
      - DATABASE_USERNAME=skg
      - DATABASE_PASSWORD=master123
      - DATABASE_NAME=skg_management
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - skg_management_data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  skg_management_data: