services:
  skg-postgres:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 54331:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - DATABASE_USERNAME: skg
      - DATABASE_PASSWORD: master123
      - DATABASE_NAME: skg
      - TZ=Asia/Ho_Chi_Minh


  skg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "3030:3030"
    depends_on:
      - skg-postgres

  # maildev:
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - ${MAIL_CLIENT_PORT}:1080
  #     - ${MAIL_PORT}:1025

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379